"""add email column to suers

Revision ID: 2453ae5e2053
Revises: bc5a9b62eab4
Create Date: 2025-10-22 16:10:21.809629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2453ae5e2053'
down_revision: Union[str, None] = 'bc5a9b62eab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_matches', sa.Column('status', sa.String(length=50), server_default='pending', nullable=False))
    op.add_column('ip_matches', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip_matches', 'reviewed_at')
    op.drop_column('ip_matches', 'status')
    # ### end Alembic commands ###
