"""add_comprehensive_dmca_fields

Revision ID: bc5a9b62eab4
Revises: a714fd3e0cf2
Create Date: 2025-10-21 00:08:04.138593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5a9b62eab4'
down_revision: Union[str, None] = 'a714fd3e0cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dmca_reports', sa.Column('original_asset_id', sa.Integer(), nullable=True))
    op.add_column('dmca_reports', sa.Column('infringement_group_id', sa.String(length=50), nullable=True))
    op.add_column('dmca_reports', sa.Column('suspected_image_url', sa.String(length=1000), nullable=True))
    op.add_column('dmca_reports', sa.Column('thumbnail_url', sa.String(length=1000), nullable=True))
    op.add_column('dmca_reports', sa.Column('source_domain', sa.String(length=255), nullable=True))
    op.add_column('dmca_reports', sa.Column('source_name', sa.String(length=255), nullable=True))
    op.add_column('dmca_reports', sa.Column('is_product', sa.Boolean(), nullable=True))
    op.add_column('dmca_reports', sa.Column('product_price', sa.String(length=50), nullable=True))
    op.add_column('dmca_reports', sa.Column('product_currency', sa.String(length=10), nullable=True))
    op.add_column('dmca_reports', sa.Column('marketplace', sa.String(length=100), nullable=True))
    op.add_column('dmca_reports', sa.Column('serp_position', sa.Integer(), nullable=True))
    op.add_column('dmca_reports', sa.Column('page_snippet', sa.Text(), nullable=True))
    op.add_column('dmca_reports', sa.Column('source_logo', sa.String(length=500), nullable=True))
    op.add_column('dmca_reports', sa.Column('best_guess', sa.String(length=255), nullable=True))
    op.add_column('dmca_reports', sa.Column('image_width', sa.Integer(), nullable=True))
    op.add_column('dmca_reports', sa.Column('image_height', sa.Integer(), nullable=True))
    op.add_column('dmca_reports', sa.Column('image_format', sa.String(length=20), nullable=True))
    op.add_column('dmca_reports', sa.Column('raw_serp_data', sa.JSON(), nullable=True))
    op.add_column('dmca_reports', sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'dmca_reports', 'ip_assets', ['original_asset_id'], ['id'])
    op.add_column('ip_assets', sa.Column('serp_raw_data', sa.JSON(), nullable=True))
    op.add_column('ip_matches', sa.Column('scraped_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip_matches', 'scraped_data')
    op.drop_column('ip_assets', 'serp_raw_data')
    op.drop_constraint(None, 'dmca_reports', type_='foreignkey')
    op.drop_column('dmca_reports', 'detected_at')
    op.drop_column('dmca_reports', 'raw_serp_data')
    op.drop_column('dmca_reports', 'image_format')
    op.drop_column('dmca_reports', 'image_height')
    op.drop_column('dmca_reports', 'image_width')
    op.drop_column('dmca_reports', 'best_guess')
    op.drop_column('dmca_reports', 'source_logo')
    op.drop_column('dmca_reports', 'page_snippet')
    op.drop_column('dmca_reports', 'serp_position')
    op.drop_column('dmca_reports', 'marketplace')
    op.drop_column('dmca_reports', 'product_currency')
    op.drop_column('dmca_reports', 'product_price')
    op.drop_column('dmca_reports', 'is_product')
    op.drop_column('dmca_reports', 'source_name')
    op.drop_column('dmca_reports', 'source_domain')
    op.drop_column('dmca_reports', 'thumbnail_url')
    op.drop_column('dmca_reports', 'suspected_image_url')
    op.drop_column('dmca_reports', 'infringement_group_id')
    op.drop_column('dmca_reports', 'original_asset_id')
    # ### end Alembic commands ###
