"""create ip tables

Revision ID: e76b52702594
Revises: b047af313d35
Create Date: 2025-09-19 02:14:35.174149

"""
from typing import Sequence, Union
import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76b52702594'
down_revision: Union[str, None] = 'b047af313d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_page_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('page_title', sa.String(length=255), nullable=True),
    sa.Column('img_alt', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('phash', sa.String(length=16), nullable=True),
    sa.Column('s3_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_index(op.f('ix_images_phash'), 'images', ['phash'], unique=False)
    op.create_index(op.f('ix_images_sha256'), 'images', ['sha256'], unique=True)
    op.create_table('image_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_embeddings_id'), 'image_embeddings', ['id'], unique=False)
    op.create_table('ip_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_assets_id'), 'ip_assets', ['id'], unique=False)
    op.create_table('ip_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['ip_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_embeddings_id'), 'ip_embeddings', ['id'], unique=False)
    op.create_table('ip_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_asset_id', sa.Integer(), nullable=False),
    sa.Column('matched_asset_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['matched_asset_id'], ['ip_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['ip_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_matches_id'), 'ip_matches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ip_matches_id'), table_name='ip_matches')
    op.drop_table('ip_matches')
    op.drop_index(op.f('ix_ip_embeddings_id'), table_name='ip_embeddings')
    op.drop_table('ip_embeddings')
    op.drop_index(op.f('ix_ip_assets_id'), table_name='ip_assets')
    op.drop_table('ip_assets')
    op.drop_index(op.f('ix_image_embeddings_id'), table_name='image_embeddings')
    op.drop_table('image_embeddings')
    op.drop_index(op.f('ix_images_sha256'), table_name='images')
    op.drop_index(op.f('ix_images_phash'), table_name='images')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
