"""update notifications and relationships

Revision ID: f52cc1921948
Revises: d1b34858cd62
Create Date: 2025-10-04 15:22:20.564675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52cc1921948'
down_revision: Union[str, None] = 'd1b34858cd62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('match_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'ip_assets', ['asset_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'ip_matches', ['match_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'asset_id')
    op.drop_column('notifications', 'match_id')
    # ### end Alembic commands ###
